---
abstract: ~
author:
  - 'Tara L Andrews <aurum@cpan.org>'
build_requires:
  Text::WagnerFischer::Armenian: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Text::TEI::Collate
name: Text-TEI-Collate
no_index:
  directory:
    - inc
    - t
recommends:
  Text::WagnerFischer: 0
requires:
  Algorithm::Diff: 0
  XML::LibXML: 0
  perl: 5.008003
version: 1.0
